[advisories]
vulnerability = "deny"
yanked = "deny"

[licenses]
# Adjust as needed for your org
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "Unicode-DFS-2016"]
copyleft = "deny"
default = "deny"
unused = "deny"

[bans]
multiple-versions = "warn"
wildcard-deps = "deny"
